export {default as PostsList} from "./PostsList/PostsList";
export {default as Home} from "./Home/Home";
export {default as SinglePost} from "./SinglePost/SinglePost";
export {default as SearchBar} from "./SearchBar/SearchBar";
export {default as NewPost} from "./NewPost/NewPost";
export {default as Delete} from "./Delete/Delete";
export {default as Register} from "./Register/Register";
export {default as NavBar} from "./NavBar/NavBar";
export {default as Login} from "./Login/Login"
export {default as PostMessage} from "./PostMessage/PostMessage"
export {default as Profile} from "./Profile/Profile"